plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include:
 - _pages

# Site Settings
locale                   : "en-US"
title                    : "Joseph Brunet"
title_separator          : "-"
name                     : "Joseph Brunet"
description              : "PhD student at Ecole des Mines de Saint-Etienne"
url                      : https://josephbrunet.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "josephbrunet.github.io"
lang                     : "en"


# Site Author
author:
  name             : "Joseph Brunet"
  avatar           : "profile.png"
  bio              : "PhD student at Ecole des Mines de Saint-Etienne, interested in vascular biomechanics"
  location         : "Saint-Etienne, France"
  employer         : Ecole des Mines de Saint-Etienne
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "https://scholar.google.com/citations?user=7T_yo4UAAAAJ&hl=en&oi=sra"
  email            : "joseph.brune@emse.fr"
  researchgate     : "https://www.researchgate.net/profile/Joseph_Brunet"
  github           : #"https://github.com/JosephBrunet"
  instagram        :
  linkedin         : "https://www.linkedin.com/in/joseph-brunet-b86b3b153"
  orcid            : "https://orcid.org/0000-0002-8424-9510"
  twitter          : #"replacethistwitterhandle"
